In [54]:
import numpy as np 
import pandas as pd  
import matplotlib.pyplot as plt
import seaborn as sns 
import datetime
import math
import matplotlib
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from keras.models import Sequential
from keras.layers import Dense , Input , Activation
from keras.optimizers import Adam
from sklearn import metrics
from sklearn.linear_model import LinearRegression


sns.set(style='darkgrid' , palette= 'deep')

In [55]:
import warnings
warnings.filterwarnings('ignore')

In [56]:
df = pd.read_csv('../data/kc_house_data.csv')
df

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,...,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,...,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,...,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21608,263000018,20140521T000000,360000.0,3,2.50,1530,1131,3.0,0,0,...,8,1530,0,2009,0,98103,47.6993,-122.346,1530,1509
21609,6600060120,20150223T000000,400000.0,4,2.50,2310,5813,2.0,0,0,...,8,2310,0,2014,0,98146,47.5107,-122.362,1830,7200
21610,1523300141,20140623T000000,402101.0,2,0.75,1020,1350,2.0,0,0,...,7,1020,0,2009,0,98144,47.5944,-122.299,1020,2007
21611,291310100,20150116T000000,400000.0,3,2.50,1600,2388,2.0,0,0,...,8,1600,0,2004,0,98027,47.5345,-122.069,1410,1287
21612,1523300157,20141015T000000,325000.0,2,0.75,1020,1076,2.0,0,0,...,7,1020,0,2008,0,98144,47.5941,-122.299,1020,1357

In [57]:
df.nunique()

id               21436
date               372
price             4028
bedrooms            13
bathrooms           30
sqft_living       1038
sqft_lot          9782
floors               6
waterfront           2
view                 5
condition            5
grade               12
sqft_above         946
sqft_basement      306
yr_built           116
yr_renovated        70
zipcode             70
lat               5034
long               752
sqft_living15      777
sqft_lot15        8689
dtype: int64

In [58]:
df.isnull().sum()

id               0
date             0
price            0
bedrooms         0
bathrooms        0
sqft_living      0
sqft_lot         0
floors           0
waterfront       0
view             0
condition        0
grade            0
sqft_above       0
sqft_basement    0
yr_built         0
yr_renovated     0
zipcode          0
lat              0
long             0
sqft_living15    0
sqft_lot15       0
dtype: int64

In [59]:
df = df.drop_duplicates()

In [60]:
df = df.drop('id',axis=1)

In [61]:
df['date'] = pd.to_datetime(df['date'])
df['month'] = df['date'].apply(lambda date : date.month)
df['year'] = df['date'].apply(lambda date : date.year)

In [62]:
df = df.drop('date',axis=1)

In [63]:
df.corr()['price'].sort_values(ascending=False)

price            1.000000
sqft_living      0.702035
grade            0.667434
sqft_above       0.605567
sqft_living15    0.585379
bathrooms        0.525138
view             0.397293
sqft_basement    0.323816
bedrooms         0.308350
lat              0.307003
waterfront       0.266369
floors           0.256794
yr_renovated     0.126434
sqft_lot         0.089661
sqft_lot15       0.082447
yr_built         0.054012
condition        0.036362
long             0.021626
year             0.003576
month           -0.010081
zipcode         -0.053203
Name: price, dtype: float64

In [64]:
df['yr_renovated'] = df['yr_renovated'].apply(lambda yr : 0 if yr==0 else 1)

In [65]:
x = df.drop('price',axis=1).values
y = df['price'].values

In [66]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)
scaler = MinMaxScaler()
X_train= scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [67]:
model = Sequential()

model.add(Dense(20,activation='relu'))
model.add(Dense(32,activation='relu'))
model.add(Dense(32,activation='relu'))
model.add(Dense(64,activation='relu'))
model.add(Dense(1))

model.compile(optimizer='adam',loss='mse')

In [68]:
model.fit(x=X_train,y=y_train, validation_data=(X_test,y_test), batch_size=128,epochs=50)

Epoch 1/50
119/119 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 414269112320.0000 - val_loss: 441674989568.0000
Epoch 2/50
119/119 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 403458654208.0000 - val_loss: 398150729728.0000
Epoch 3/50
119/119 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 346205913088.0000 - val_loss: 155004174336.0000
Epoch 4/50
119/119 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 110247780352.0000 - val_loss: 108998008832.0000
Epoch 5/50
119/119 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 88954855424.0000 - val_loss: 105987047424.0000
Epoch 6/50
119/119 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 83682238464.0000 - val_loss: 102865633280.0000
Epoch 7/50
119/119 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 97126449152.0000 - val_loss: 99677773824.0000
Epoch 8/50
119/119 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 89059950592.0000 - val_loss: 95950929920.0000
Epoch 9/50
119/119 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 84430503936.0000 - val_loss: 92229844992.0000
Epoch 10/50
119/119 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 84335484928.0000 - val_loss: 87893426176.0000
Epoch 11/50
119/119 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 75777564672.0000 - val_loss: 83282100224.0000
Epoch 12/50
119/119 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 69730713600.0000 - val_loss: 78573395968.0000
Epoch 13/50
119/119 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 73048875008.0000 - val_loss: 73747611648.0000
Epoch 14/50
119/119 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 64789327872.0000 - val_loss: 69003673600.0000
Epoch 15/50
119/119 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 59905597440.0000 - val_loss: 64686620672.0000
Epoch 16/50
119/119 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 56950915072.0000 - val_loss: 61027061760.0000
Epoch 17/50
119/119 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 58611871744.0000 - val_loss: 57997279232.0000
Epoch 18/50
119/119 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 47240134656.0000 - val_loss: 55779762176.0000
Epoch 19/50
119/119 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50901524480.0000 - val_loss: 54003539968.0000
Epoch 20/50
119/119 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 46317531136.0000 - val_loss: 52492075008.0000
Epoch 21/50
119/119 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 45709787136.0000 - val_loss: 51374391296.0000
Epoch 22/50
119/119 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 44384190464.0000 - val_loss: 50060754944.0000
Epoch 23/50
119/119 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 43120201728.0000 - val_loss: 49057181696.0000
Epoch 24/50
119/119 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 41321181184.0000 - val_loss: 48142618624.0000
Epoch 25/50
119/119 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 40372195328.0000 - val_loss: 47254798336.0000
Epoch 26/50
119/119 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 42326147072.0000 - val_loss: 46536949760.0000
Epoch 27/50
119/119 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 41965473792.0000 - val_loss: 45784170496.0000
Epoch 28/50
119/119 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 39967068160.0000 - val_loss: 45028175872.0000
Epoch 29/50
119/119 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 42423898112.0000 - val_loss: 44320256000.0000
Epoch 30/50
119/119 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 39045292032.0000 - val_loss: 43642929152.0000
Epoch 31/50
119/119 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 36982988800.0000 - val_loss: 43045240832.0000
Epoch 32/50
119/119 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 40115937280.0000 - val_loss: 42469036032.0000
Epoch 33/50
119/119 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 37828481024.0000 - val_loss: 42054447104.0000
Epoch 34/50
119/119 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 37788459008.0000 - val_loss: 41534021632.0000
Epoch 35/50
119/119 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 37149179904.0000 - val_loss: 41070395392.0000
Epoch 36/50
119/119 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 35126894592.0000 - val_loss: 40654123008.0000
Epoch 37/50
119/119 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 34228105216.0000 - val_loss: 40362831872.0000
Epoch 38/50
119/119 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 38066135040.0000 - val_loss: 39922667520.0000
Epoch 39/50
119/119 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 36226379776.0000 - val_loss: 39623086080.0000
Epoch 40/50
119/119 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 38283505664.0000 - val_loss: 39270035456.0000
Epoch 41/50
119/119 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 34712367104.0000 - val_loss: 39042306048.0000
Epoch 42/50
119/119 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 36744781824.0000 - val_loss: 38720778240.0000
Epoch 43/50
119/119 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 34424029184.0000 - val_loss: 38492901376.0000
Epoch 44/50
119/119 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 32039225344.0000 - val_loss: 38290042880.0000
Epoch 45/50
119/119 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 32978589696.0000 - val_loss: 38286888960.0000
Epoch 46/50
119/119 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 32999518208.0000 - val_loss: 38006607872.0000
Epoch 47/50
119/119 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 32857268224.0000 - val_loss: 37810561024.0000
Epoch 48/50
119/119 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 31622860800.0000 - val_loss: 37768994816.0000
Epoch 49/50
119/119 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 33642096640.0000 - val_loss: 37516369920.0000
Epoch 50/50
119/119 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 32110034944.0000 - val_loss: 37370048512.0000